import { useRouter } from "next/router";
import Image from "next/image";
import Head from "next/head";
// component
import Login from "@/components/Login";

import styles from "../styles/LoginPage.module.scss"
import logo from "../../public/Images/logo-myeshop.png";


const LogIn = () => {

    const router = useRouter()


    return (
      <>
        <Head>
          <title>MyeShop</title>
          <meta name="description" content="Generated by create next app" />
          <meta name="viewport" content="width=device-width, initial-scale=1" />
          <link rel="icon" href="/icon-myeshop.ico" />
        </Head>
        <div className={styles.Login_navbar}>
          <Image
            onClick={() => router.push("/")}
            src={logo}
            className={styles.Login_logo}
          />
        </div>
        <Login />
      </>
    );
}

export default LogIn;